name: hapi-new-12
base: core18
version: '1.0.11'
summary: Hapi Server Linux-x64
description: |
  Hapi Server Linux-x64
grade: devel
confinement: devmode
architectures:
  - build-on: amd64

apps:
  curl:
    command: curl
  hapis1:
     command: /snap/hapi-new-12/current/hapi-server-v1.0.11/bin/node /snap/hapi-new-12/current/hapi-server-v1.0.11/test/server-test.js --logdir="/home/log" --metadir="/home/meta"
  hapis-server:
    command: /snap/hapi-new-12/current/hapi-server-v1.0.11/hapi-server --logdir="/home/log" --metadir="/home/meta" 


  
parts:
  hapis1:
    source: https://github.com/drunkenlord/snapp-happ/releases/download/v1.0.11/hapi-server-v1.0.11.tgz
    plugin: dump
  hapis-server:
    source: https://github.com/drunkenlord/snapp-happ/releases/download/v1.0.11/hapi-server-v1.0.11.tgz
    plugin: dump
  curl:
    source: http://curl.haxx.se/download/curl-7.45.0.tar.bz2
    plugin: autotools
