name: hapi-combo11
base: core18
version: '1.0.11'
summary: Hapi Server Linux-x64
description: |
  Hapi Server Linux-x64
grade: stable
confinement: strict
architectures:
  - build-on: amd64

apps:
  curl:
    command: curl
  hapis1:
     command: hapi-server-v1.0.10/bin/node hapi-server-v1.0.10/test/server-test.js
  hapis-server:
    command: hapi-server-v1.0.10/hapi-server --logdir="/var/snap/hapi-combo11/current" --metadata_dir="/var/snap/hapi-combo11/current" 


  
parts:
  hapis1:
    source: https://github.com/drunkenlord/snapp-happ/releases/download/v1.0.0.1/hapi-server-v1.0.10.tar.gz
    plugin: dump
  hapis-server:
    source: https://github.com/drunkenlord/snapp-happ/releases/download/v1.0.0.1/hapi-server-v1.0.10.tar.gz
    plugin: dump
  curl:
    source: http://curl.haxx.se/download/curl-7.45.0.tar.bz2
    plugin: autotools


#####
