name: hapi-combo7
base: core18
version: '1.0.11'
summary: Hapi Server Linux-x64
description: |
  Hapi Server Linux-x64
grade: devel
confinement: devmode
architectures:
  - build-on: amd64

apps:
  curl:
    command: curl
  # bash:
  #   command: bash
  hapis1:
     command: /snap/hapi-combo7/current/hapi-server-v1.0.10/bin/node /snap/hapi-combo7/current/hapi-server-v1.0.10/test/server-test.js
  hapis-server:
    command: /snap/hapi-combo7/current/hapi-server-v1.0.10/hapi-server --logdir="/home/hapi_logs" --metadata_dir="/home/hapi_metadata" 

  
parts:
  hapis1:
    source: https://github.com/drunkenlord/snapp-happ/releases/download/v1.0.0.0/hapi-server-v1.0.10.tar.gz
    plugin: dump
  hapis-server:
    source: https://github.com/drunkenlord/snapp-happ/releases/download/v1.0.0.0/hapi-server-v1.0.10.tar.gz
    plugin: dump
  curl:
    source: http://curl.haxx.se/download/curl-7.45.0.tar.bz2
    plugin: autotools